from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class EventType(StrEnum):
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_REJECTED = "WEBHOOK_REJECTED"
    PR_LOADED = "PR_LOADED"
    PLANNING_STARTED = "PLANNING_STARTED"

    AGENT_QUEUED = "AGENT_QUEUED"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_THINKING_SUMMARY = "AGENT_THINKING_SUMMARY"
    AGENT_TOOL_STARTED = "AGENT_TOOL_STARTED"
    AGENT_TOOL_COMPLETED = "AGENT_TOOL_COMPLETED"
    TOOL_RESULT_CACHE_HIT = "TOOL_RESULT_CACHE_HIT"
    AGENT_MESSAGE_SENT = "AGENT_MESSAGE_SENT"
    AGENT_MESSAGE_RECEIVED = "AGENT_MESSAGE_RECEIVED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_SKIPPED = "AGENT_SKIPPED"

    EDGE_EVALUATED = "EDGE_EVALUATED"
    EDGE_TRIGGERED = "EDGE_TRIGGERED"
    EDGE_SKIPPED = "EDGE_SKIPPED"

    FINDING_CREATED = "FINDING_CREATED"
    FINDING_VALIDATED = "FINDING_VALIDATED"
    FINDING_REJECTED = "FINDING_REJECTED"
    FINDING_CRITICIZED = "FINDING_CRITICIZED"

    REPLAN_STARTED = "REPLAN_STARTED"
    REPLAN_COMPLETED = "REPLAN_COMPLETED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    DEBATE_STARTED = "DEBATE_STARTED"
    DEBATE_RESOLVED = "DEBATE_RESOLVED"

    HIGH_SEVERITY_FINDING_CONFIRMED = "HIGH_SEVERITY_FINDING_CONFIRMED"
    AGENT_DYNAMICALLY_ACTIVATED = "AGENT_DYNAMICALLY_ACTIVATED"

    REVIEW_GENERATED = "REVIEW_GENERATED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_DECIDED = "APPROVAL_DECIDED"
    GITHUB_UPDATED = "GITHUB_UPDATED"
    JIRA_UPDATED = "JIRA_UPDATED"

    TOKEN_USAGE_RECORDED = "TOKEN_USAGE_RECORDED"
    REVIEW_FAILED = "REVIEW_FAILED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"

    CHAOS_FAILURE_INJECTED = "CHAOS_FAILURE_INJECTED"
    CHAOS_RETRY_SUCCEEDED = "CHAOS_RETRY_SUCCEEDED"

    INCREMENTAL_REVIEW_STARTED = "INCREMENTAL_REVIEW_STARTED"
    FINDING_CLASSIFIED = "FINDING_CLASSIFIED"
    INCREMENTAL_REVIEW_COMPLETED = "INCREMENTAL_REVIEW_COMPLETED"


class Event(BaseModel):
    id: str
    type: EventType
    review_id: str
    timestamp: str
    payload: dict[str, Any] = Field(default_factory=dict)
